"""Add level column

Revision ID: 0642a63f1c0e
Revises: 878810bb7fa9
Create Date: 2023-12-28 13:15:59.998542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0642a63f1c0e'
down_revision: Union[str, None] = '878810bb7fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('level', sa.String(), server_default='Senior', nullable=True))
    op.add_column('fightstatistics', sa.Column('defense_reason', sa.Boolean(), nullable=False))
    op.alter_column('fightstatistics', 'action_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('fightstatistics', 'fighter_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('fighter_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('fightstatistics', 'action_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('fightstatistics', 'defense_reason')
    op.drop_column('fightinfos', 'level')
    # ### end Alembic commands ###
