"""change string lengt fighter

Revision ID: 1506420298a6
Revises: e301128434ca
Create Date: 2024-01-15 21:36:22.589427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1506420298a6'
down_revision: Union[str, None] = 'e301128434ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fighters', 'natinality_name',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fighters', 'natinality_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
