"""add status fightinfos

Revision ID: 1bc72395b6d2
Revises: c698b0a581b6
Create Date: 2024-01-18 11:55:40.061365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc72395b6d2'
down_revision: Union[str, None] = 'c698b0a581b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('status', sa.String(length=50), server_default='not started', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightinfos', 'status')
    # ### end Alembic commands ###
