"""Add action name table

Revision ID: 33b1d17544a2
Revises: c395181f8486
Create Date: 2023-12-19 16:55:30.754461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1d17544a2'
down_revision: Union[str, None] = 'c395181f8486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fightstatistics', sa.Column('action_number', sa.Integer(), nullable=False))
    op.add_column('fightstatistics', sa.Column('action_name_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fightstatistics', 'actions', ['action_name_id'], ['id'])
    op.drop_column('fightstatistics', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fightstatistics', type_='foreignkey')
    op.drop_column('fightstatistics', 'action_name_id')
    op.drop_column('fightstatistics', 'action_number')
    op.drop_table('actions')
    # ### end Alembic commands ###
