"""

Revision ID: 47ce59983414
Revises: 64b4f09329c8
Create Date: 2024-01-26 16:50:04.086592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ce59983414'
down_revision: Union[str, None] = '64b4f09329c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fightinfos_tournament_id_fkey', 'fightinfos', type_='foreignkey')
    op.create_foreign_key(None, 'fightinfos', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fightinfos', type_='foreignkey')
    op.create_foreign_key('fightinfos_tournament_id_fkey', 'fightinfos', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
