"""add dates into fightinfo

Revision ID: 58905ea144d5
Revises: 700b34b01103
Create Date: 2024-01-26 11:26:47.260718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58905ea144d5'
down_revision: Union[str, None] = '700b34b01103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('submited_date', sa.Date(), nullable=True))
    op.add_column('fightinfos', sa.Column('checked_date', sa.Date(), nullable=True))
    op.add_column('fightinfos', sa.Column('created_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightinfos', 'created_date')
    op.drop_column('fightinfos', 'checked_date')
    op.drop_column('fightinfos', 'submited_date')
    # ### end Alembic commands ###
