"""Add opponents points

Revision ID: 5c9ea1d3bf01
Revises: 5f825feceafd
Create Date: 2023-12-21 17:02:35.031820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c9ea1d3bf01'
down_revision: Union[str, None] = '5f825feceafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('oponent1_point', sa.Integer(), nullable=False))
    op.add_column('fightinfos', sa.Column('oponent2_point', sa.Integer(), nullable=False))
    op.alter_column('fightinfos', 'decision',
               existing_type=postgresql.ENUM('VPO1', 'VSU', 'VPO', 'VFO', 'VIN', 'VFA', name='decisionenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fightinfos', 'decision',
               existing_type=postgresql.ENUM('VPO1', 'VSU', 'VPO', 'VFO', 'VIN', 'VFA', name='decisionenum'),
               nullable=True)
    op.drop_column('fightinfos', 'oponent2_point')
    op.drop_column('fightinfos', 'oponent1_point')
    # ### end Alembic commands ###
