"""add fields to null

Revision ID: 64ad585a30b0
Revises: 0642a63f1c0e
Create Date: 2024-01-13 15:45:55.341169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ad585a30b0'
down_revision: Union[str, None] = '0642a63f1c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.alter_column('fightstatistics', 'action_time',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('fightstatistics', 'video_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fightstatistics', 'video_link',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('fightstatistics', 'action_time',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('fightinfos', 'is_submitted')
    # ### end Alembic commands ###
