"""delete author field from  fightstatistic

Revision ID: 684045a68671
Revises: 747d1ee3dfd5
Create Date: 2024-02-07 13:49:07.680311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684045a68671'
down_revision: Union[str, None] = '747d1ee3dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightstatistics', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
