"""add cascade into fightsatistic

Revision ID: 700b34b01103
Revises: e93fdc2b62c0
Create Date: 2024-01-26 10:40:59.441660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700b34b01103'
down_revision: Union[str, None] = 'e93fdc2b62c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fightstatistics_fight_id_fkey', 'fightstatistics', type_='foreignkey')
    op.create_foreign_key(None, 'fightstatistics', 'fightinfos', ['fight_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fightstatistics', type_='foreignkey')
    op.create_foreign_key('fightstatistics_fight_id_fkey', 'fightstatistics', 'fightinfos', ['fight_id'], ['id'])
    # ### end Alembic commands ###
