"""add flag field  logic to fightstatistic

Revision ID: 747d1ee3dfd5
Revises: 4a1b994dcd15
Create Date: 2024-02-07 12:31:18.528210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747d1ee3dfd5'
down_revision: Union[str, None] = '4a1b994dcd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('flag', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightstatistics', 'flag')
    # ### end Alembic commands ###
