"""change natinality forign key to string

Revision ID: 95f7b6e94b86
Revises: 5c9ea1d3bf01
Create Date: 2023-12-21 17:20:21.569032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f7b6e94b86'
down_revision: Union[str, None] = '5c9ea1d3bf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('natinality_name', sa.String(length=5), nullable=False))
    op.drop_constraint('fighters_nationality_id_fkey', 'fighters', type_='foreignkey')
    op.drop_column('fighters', 'nationality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighters', sa.Column('nationality_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fighters_nationality_id_fkey', 'fighters', 'nationalities', ['nationality_id'], ['id'])
    op.drop_column('fighters', 'natinality_name')
    # ### end Alembic commands ###
