"""Initial migration.

Revision ID: c395181f8486
Revises: 
Create Date: 2023-12-19 16:28:49.338767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c395181f8486'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('level', sa.Enum('Seniors', 'U17', 'U20', 'U23', 'Veterans', name='levelenum'), nullable=False),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fightinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('oponent_id', sa.Integer(), nullable=False),
    sa.Column('wrestling_type', sa.Enum('Freestyle', name='wrestlingtypeenum'), nullable=False),
    sa.Column('fight_date', sa.Date(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('weight_category', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.Enum('Qualification', 'onesixteen', 'oneeighth', 'onequarter', 'onehalf', 'Final', name='stageenum'), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['oponent_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fightstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.String(length=15), nullable=False),
    sa.Column('action_time_second', sa.Integer(), nullable=False),
    sa.Column('fighter_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('video_second_begin', sa.TIMESTAMP(), nullable=True),
    sa.Column('video_second_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('video_link', sa.String(length=100), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['fightinfos.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fightstatistics')
    op.drop_table('fightinfos')
    op.drop_table('fighters')
    op.drop_table('tournaments')
    op.drop_table('techniques')
    op.drop_table('nationalities')
    # ### end Alembic commands ###
