"""add opponent relat fightstatistic

Revision ID: c698b0a581b6
Revises: a7a7cad883eb
Create Date: 2024-01-17 15:02:05.824784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c698b0a581b6'
down_revision: Union[str, None] = 'a7a7cad883eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('opponent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fightstatistics', 'fighters', ['opponent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fightstatistics', type_='foreignkey')
    op.drop_column('fightstatistics', 'opponent_id')
    # ### end Alembic commands ###
