"""first migrate

Revision ID: e301128434ca
Revises: 
Create Date: 2024-01-15 21:02:05.749023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e301128434ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('natinality_name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fightinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wrestling_type', sa.String(), nullable=False),
    sa.Column('fight_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('weight_category', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('oponent1_point', sa.Integer(), nullable=False),
    sa.Column('oponent2_point', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), server_default='Senior', nullable=True),
    sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('oponent_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['oponent_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fightstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_time_second', sa.Integer(), nullable=False),
    sa.Column('action_number', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('video_second_begin', sa.TIMESTAMP(), nullable=True),
    sa.Column('video_second_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('video_link', sa.String(length=100), nullable=True),
    sa.Column('defense_reason', sa.Boolean(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('action_name_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_name_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['fight_id'], ['fightinfos.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fightstatistics')
    op.drop_table('fightinfos')
    op.drop_table('tournaments')
    op.drop_table('techniques')
    op.drop_table('nationalities')
    op.drop_table('fighters')
    op.drop_table('actions')
    # ### end Alembic commands ###
