"""add source_type field fightinfos

Revision ID: e93fdc2b62c0
Revises: 1bc72395b6d2
Create Date: 2024-01-25 12:41:50.884668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93fdc2b62c0'
down_revision: Union[str, None] = '1bc72395b6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightinfos', sa.Column('source_type', sa.String(length=20), server_default='app', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightinfos', 'source_type')
    # ### end Alembic commands ###
