"""add author to statistic model

Revision ID: ebb04890091e
Revises: 64ad585a30b0
Create Date: 2024-01-15 13:03:41.037557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb04890091e'
down_revision: Union[str, None] = '64ad585a30b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightstatistics', sa.Column('author', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightstatistics', 'author')
    # ### end Alembic commands ###
