"""Add winner and desition colum in fight info

Revision ID: fc43347575c3
Revises: 33b1d17544a2
Create Date: 2023-12-21 15:55:58.392082

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc43347575c3'
down_revision: Union[str, None] = '33b1d17544a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    decision_enum = postgresql.ENUM('VPO1', 'VSU', 'VPO', 'VFO', 'VIN', 'VFA', name='decisionenum', create_type=False)
    decision_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('fightinfos', sa.Column('type', decision_enum, nullable=True))
    op.add_column('fightinfos', sa.Column('winner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fightinfos', 'fighters', ['winner_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fightinfos', type_='foreignkey')
    op.drop_column('fightinfos', 'winner_id')
    op.drop_column('fightinfos', 'type')
    postgresql.ENUM(name='decisionenum').drop(op.get_bind(), checkfirst=True)

# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'fightinfos', type_='foreignkey')
#     op.drop_column('fightinfos', 'winner_id')
#     op.drop_column('fightinfos', 'decision')
#     # ### end Alembic commands ###


# op.add_column('fightinfos', sa.Column('decision', sa.Enum('VPO1', 'VSU', 'VPO', 'VFO', 'VIN', 'VFA', name='decisionenum'), nullable=False))